FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y g++
RUN apt-get update && apt-get install -y cmake
RUN apt-get update && apt-get install -y libpng-dev


WORKDIR /face_rec

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

CMD [ "python", "library_rec.py" ]
