FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip uninstall flask
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD echo "This is a test." | wc -
#CMD [ "python", "server.py" ]
