version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - my-network
  face_rec:
    build: ./face_rec
    networks:
      - my-network
  mail:
    build: ./mail
    networks:
      - my-network
networks:
  my-network:
